dist: xenial
sudo: required
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt594-xenial
  - travis_retry sudo apt-get update
  - travis_wait 30 sudo apt-get -y install -qq mesa-common-dev qt59-meta-full qt59charts-no-lgpl qt59gamepad qt59connectivity 

script:
  - source /opt/qt59/bin/qt59-env.sh 
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_DEBIAN=ON -DWITH_GAMEPAD=ON 
  - make -j4
